### ISSUE TITLE
cannot import name 'ConvertModel'

### ISSUE THREAD

**Issue by theangels** [Talmaj/onnx2pytorch#12]
I install onnx2pytorch with `pip install onnx2pytorch` and run sample code:

``` python
import onnx
from onnx2pytorch import ConvertModel

path_to_onnx_model = 'model.onnx'

onnx_model = onnx.load(path_to_onnx_model)

pytorch_model = ConvertModel(onnx_model)
```

Then it display it:

``` text
Traceback (most recent call last):
  File "onnx2pytorch.py", line 2, in <module>
    from onnx2pytorch import ConvertModel
  File "D:\机器学习\Onnx\onnx2pytorch.py", line 2, in <module>
    from onnx2pytorch import ConvertModel
ImportError: cannot import name 'ConvertModel'
```

My system is Windows 10, and python version is 3.6

**Comment by Talmaj** [comment]
Hi, does ```from onnx2pytorch.convert.model import ConvertModel``` work for you?
